# Generated by Django 2.0.5 on 2018-05-14 22:42

import api.models
from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date_value', models.DateField(editable=False, unique=True)),
            ],
            options={
                'ordering': ('date_value',),
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('as_student', models.BooleanField(default=False)),
                ('total_fee_amount', api.models.MoneyField(decimal_places=2, editable=False, max_digits=8)),
                ('paid_fee_amount', api.models.MoneyField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('attending_dates', models.ManyToManyField(to='api.Date')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('fee', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('student_discount', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('track_order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(default='', max_length=2000)),
                ('comment', models.CharField(default='', max_length=2000)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='api.Registration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PLENARY', 'Plenary')], default='REGULAR', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('num_time_slots', models.PositiveIntegerField(default=4)),
                ('time_slot_duration', models.DurationField()),
                ('schedule_order', models.PositiveIntegerField()),
                ('rooms', models.ManyToManyField(to='api.Room')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_sessions', to='api.TalkSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='TalkTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(default='', max_length=100)),
                ('session_order', models.PositiveIntegerField()),
                ('chair', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_tracks', to='api.TalkSession')),
                ('talks', models.ManyToManyField(through='api.ScheduledTalk', to='api.Talk')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('affiliation', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.URLField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shortname', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_fee', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('base_student_discount', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('daily_fee', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('daily_student_discount', api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('reg_open', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scheduledtalk',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Talk'),
        ),
        migrations.AddField(
            model_name='scheduledtalk',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TalkTrack'),
        ),
        migrations.AddField(
            model_name='room',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.Workshop'),
        ),
        migrations.AddField(
            model_name='registrationoption',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_options', to='api.Workshop'),
        ),
        migrations.AddField(
            model_name='registration',
            name='options',
            field=models.ManyToManyField(to='api.RegistrationOption'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.Workshop'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='talktrack',
            unique_together={('session', 'session_order')},
        ),
        migrations.AlterUniqueTogether(
            name='talksession',
            unique_together={('schedule', 'schedule_order')},
        ),
        migrations.AlterUniqueTogether(
            name='scheduledtalk',
            unique_together={('track', 'track_order'), ('talk', 'track')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('workshop', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('workshop', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('recipient', 'workshop')},
        ),
    ]
