# Generated by Django 2.0.5 on 2018-05-15 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talksession',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0), editable=False),
        ),
    ]
