# Generated by Django 2.0.5 on 2018-05-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_talksession_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talksession',
            name='end_time',
        ),
    ]
