# Generated by Django 2.1.2 on 2018-10-09 05:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_talksession_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledtalk',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='scheduledtalk',
            name='talk',
        ),
        migrations.RemoveField(
            model_name='scheduledtalk',
            name='track',
        ),
        migrations.AlterUniqueTogether(
            name='talksession',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='talksession',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='talksession',
            name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='talktrack',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='talktrack',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='talktrack',
            name='session',
        ),
        migrations.RemoveField(
            model_name='talktrack',
            name='talks',
        ),
        migrations.AddField(
            model_name='talkschedule',
            name='talk_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ScheduledTalk',
        ),
        migrations.DeleteModel(
            name='TalkSession',
        ),
        migrations.DeleteModel(
            name='TalkTrack',
        ),
    ]
