# Generated by Django 2.1.2 on 2018-11-04 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181104_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliated_users', to='api.Affiliation'),
        ),
    ]
