# Generated by Django 2.1.2 on 2018-11-12 01:52

import api.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181104_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='as_student',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='base_fee',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='base_student_discount',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='daily_fee',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='daily_student_discount',
        ),
        migrations.AddField(
            model_name='registration',
            name='fee_type',
            field=api.models.FeeTypeField(choices=[(api.models.FeeType('Affiliate'), 'Affiliate'), (api.models.FeeType('Exempt'), 'Exempt'), (api.models.FeeType('Full'), 'Full'), (api.models.FeeType('Student'), 'Student')], default=api.models.FeeType('Full'), max_length=20),
        ),
        migrations.AddField(
            model_name='registrationoption',
            name='fee_affiliate',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='registrationoption',
            name='fee_full',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='registrationoption',
            name='fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='registrationoption',
            name='short_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='base_fee_affiliate',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('250'), max_digits=8),
        ),
        migrations.AddField(
            model_name='workshop',
            name='base_fee_full',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('250'), max_digits=8),
        ),
        migrations.AddField(
            model_name='workshop',
            name='base_fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('250'), max_digits=8),
        ),
        migrations.AddField(
            model_name='workshop',
            name='daily_fee_affiliate',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('50'), max_digits=8),
        ),
        migrations.AddField(
            model_name='workshop',
            name='daily_fee_full',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('50'), max_digits=8),
        ),
        migrations.AddField(
            model_name='workshop',
            name='daily_fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('50'), max_digits=8),
        ),
        migrations.RemoveField(
            model_name='registrationoption',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='registrationoption',
            name='student_discount',
        ),
        migrations.AlterUniqueTogether(
            name='registrationoption',
            unique_together={('workshop', 'short_title'), ('workshop', 'title')},
        ),
    ]
