# Generated by Django 2.1.2 on 2018-11-14 22:50

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181112_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fee_type',
            field=api.models.FeeTypeField(choices=[('AFFILIATE', 'Affiliate'), ('EXEMPT', 'Exempt'), ('FULL', 'Full'), ('STUDENT', 'Student')], default=api.models.FeeType('Full'), max_length=20),
        ),
    ]
