# Generated by Django 2.1.2 on 2018-11-14 23:06

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181114_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fee_type',
            field=api.models.FeeTypeField(choices=[('AFFILIATE', 'Affiliate'), ('EXEMPT', 'Exempt'), ('FULL', 'Full'), ('STUDENT', 'Student')], default='FULL', max_length=20),
        ),
    ]
