# Generated by Django 2.1.3 on 2018-11-15 23:03

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181114_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fee_type',
            field=api.models.FeeTypeField(choices=[('AFFILIATE', 'Affiliate'), ('EXEMPT', 'Exempt'), ('FULL', 'Full'), ('STUDENT', 'Student'), ('WAIVED', 'Waived')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='affiliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affiliated_users', to='api.Affiliation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
