# Generated by Django 2.1.3 on 2018-11-17 04:06

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181115_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='participation_status',
            field=api.models.ParticipationStatusField(choices=[('ALMOST_CERTAINLY', 'Almost certainly'), ('PROBABLY', 'Probably'), ('MAYBE', 'Maybe'), ('PROBABLY_NOT', 'Probably not'), ('NEXT_TIME', 'Next time')], default='ALMOST_CERTAINLY', max_length=50),
        ),
    ]
