# Generated by Django 2.1.3 on 2018-11-28 20:57

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_registration_participation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registration',
            name='presenting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='presenting_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='registrant_type',
            field=api.models.RegistrantTypeField(choices=[('INVITED', 'Invited'), ('SELF_REGISTERED', 'Self-registered')], default='SELF_REGISTERED', max_length=20),
        ),
    ]
