# Generated by Django 2.1.3 on 2018-11-29 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181128_1729'),
        ('api', '0013_auto_20181128_2057'),
    ]

    operations = [
    ]
