# Generated by Django 2.1.3 on 2018-11-29 01:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20181129_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='DEFAULT_FIRST_NAME', max_length=30, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='honorific',
            field=api.models.HonorificField(blank=True, choices=[('MISTER', 'Mr'), ('MISS', 'Ms'), ('DOCTOR', 'Dr'), ('PROFESSOR', 'Prof')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='DEFAULT_LAST_NAME', max_length=150, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
