# Generated by Django 2.1.3 on 2018-11-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0018_auto_20181129_0538'), ('api', '0019_auto_20181129_0548'), ('api', '0020_auto_20181129_0721')]

    dependencies = [
        ('api', '0017_auto_20181129_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='registration',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.UserProfile'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='api.UserProfile'),
        ),
    ]
