# Generated by Django 2.1.3 on 2018-11-29 08:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181129_0538_squashed_0020_auto_20181129_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_size',
            field=api.models.ShirtSizeField(blank=True, choices=[('SMALL', 'S'), ('MEDIUM', 'M'), ('LARGE', 'L'), ('XLARGE', 'XL'), ('XXLARGE', 'XXL')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_type',
            field=api.models.ShirtTypeField(blank=True, choices=[('MENS', "Men's"), ('WOMENS', "Women's")], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
