# Generated by Django 2.1.3 on 2018-11-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181129_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='api.UserProfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='api.UserProfile'),
        ),
    ]
