# Generated by Django 2.1.3 on 2018-11-29 19:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20181129_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='shortname',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='workshop',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[api.models.SlugValidator]),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='registrationoption',
            old_name='short_title',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='registrationoption',
            name='slug',
            field=models.CharField(max_length=50, unique=True, validators=[api.models.SlugValidator]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='registrationoption',
            unique_together={('workshop', 'title')},
        ),
    ]
