# Generated by Django 2.1.3 on 2018-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20181129_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationoption',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='registrationoption',
            unique_together=set(),
        ),
    ]
