# Generated by Django 2.1.3 on 2018-11-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181129_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_original',
            field=models.EmailField(blank=True, editable=False, max_length=255, verbose_name='original email address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_original',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='original first name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_original',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='original last name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=150, verbose_name='nickname'),
        ),
    ]
