# Generated by Django 2.1.3 on 2018-12-01 09:28

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20181130_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPayment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', api.models.MoneyField(decimal_places=2, max_digits=8)),
                ('status', api.models.RegistrationPaymentStatusField(choices=[('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='INITIATED', max_length=20)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Registration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
