# Generated by Django 2.1.3 on 2018-12-01 19:10

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_registrationpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpayment',
            name='amount',
            field=api.models.MoneyField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='registration',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.Registration'),
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='status',
            field=api.models.RegistrationPaymentStatusField(choices=[('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='INITIATED', editable=False, max_length=20),
        ),
    ]
