# Generated by Django 2.1.3 on 2018-12-02 22:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181201_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='invoice_number',
            field=models.CharField(default='', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationpayment',
            name='status',
            field=api.models.RegistrationPaymentStatusField(choices=[('INITIATED', 'Initiated'), ('CANCELED', 'Canceled'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('ERROR', 'Error'), ('HELD_FOR_REVIEW', 'Held for review')], default='INITIATED', editable=False, max_length=20),
        ),
    ]
