# Generated by Django 2.1.3 on 2018-12-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20181202_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
