# Generated by Django 2.1.3 on 2018-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_registrationpayment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_db_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='users.id in old itaweb database'),
        ),
    ]
