# Generated by Django 2.1.3 on 2018-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_old_db_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
