# Generated by Django 2.1.3 on 2018-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181204_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='presenting_default',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='presenting_default',
            field=models.BooleanField(default=False),
        ),
    ]
