# Generated by Django 2.1.3 on 2018-12-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20181204_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.URLField(blank=True, default='', max_length=250),
        ),
    ]
