# Generated by Django 2.1.4 on 2018-12-11 01:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='fee_type',
            field=api.models.FeeTypeField(blank=True, choices=[('AFFILIATE', 'Affiliate'), ('EXEMPT', 'Exempt'), ('FULL', 'Full'), ('STUDENT', 'Student'), ('WAIVED', 'Waived')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
