# Generated by Django 2.1.4 on 2018-12-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20181211_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='talk',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='talk',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
