# Generated by Django 2.1.4 on 2019-01-05 06:50

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20181213_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participation_status',
            field=api.models.ParticipationStatusField(choices=[('ALMOST_CERTAINLY', 'Almost certainly'), ('PROBABLY', 'Probably'), ('PROBABLY_NOT', 'Probably not'), ('NEXT_TIME', 'Next time')], default='ALMOST_CERTAINLY', max_length=50),
        ),
    ]
