# Generated by Django 2.1.4 on 2019-01-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20190105_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='comment',
            new_name='scheduling_comment',
        ),
        migrations.AddField(
            model_name='talk',
            name='topic_comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
