# Generated by Django 2.1.4 on 2019-01-08 08:49

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20190108_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('picture', models.ImageField(upload_to=api.models.new_profile_pic_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='old_profile_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='new_profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='api.ProfilePicture'),
        ),
    ]
