# Generated by Django 2.1.5 on 2019-01-09 01:42

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20190108_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=api.models.new_talk_paper_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talk', to='api.TalkPaper'),
        ),
    ]
