# Generated by Django 2.1.5 on 2019-01-10 03:49

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20190109_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='participation_status',
            field=api.models.ParticipationStatusField(blank=True, choices=[('ALMOST_CERTAINLY', 'Almost certainly'), ('PROBABLY', 'Probably'), ('PROBABLY_NOT', 'Probably not'), ('NEXT_TIME', 'Next time')], default='', max_length=50),
        ),
    ]
