# Generated by Django 2.1.5 on 2019-01-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20190110_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='nickname'),
        ),
    ]
