# Generated by Django 2.1.5 on 2019-01-11 07:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20190111_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approved_payments_total_amount',
            field=api.models.MoneyField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='registration',
            name='has_approved_payment',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
