# Generated by Django 2.1.5 on 2019-02-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190111_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='authors_comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
