# Generated by Django 2.1.5 on 2019-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_talk_authors_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registrant_number',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('workshop', 'registrant_number'), ('workshop', 'user')},
        ),
    ]
