# Generated by Django 2.1.5 on 2019-02-13 18:19

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20190206_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCharge',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', api.models.MoneyField(decimal_places=2, max_digits=8)),
                ('status', api.models.OneTimeChargeStatusField(choices=[('OPEN', 'Open'), ('CANCELED', 'Canceled'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('comment', models.CharField(blank=True, default='', max_length=2000)),
                ('recipient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneTimeChargePayment',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', api.models.OneTimeChargePaymentStatusField(choices=[('INITIATED', 'Initiated'), ('CANCELED', 'Canceled'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('ERROR', 'Error'), ('HELD_FOR_REVIEW', 'Held for review')], default='INITIATED', editable=False, max_length=20)),
                ('invoice_number', models.CharField(editable=False, max_length=20)),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=50)),
                ('charge', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='api.OneTimeCharge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
