# Generated by Django 2.1.5 on 2020-01-31 22:36

import api.models
from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_onetimecharge_onetimechargepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationpayment',
            name='continue_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='daily_fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('35'), max_digits=8),
        ),
    ]
