# Generated by Django 2.1.5 on 2020-06-28 07:18

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200131_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=api.models.new_talk_video_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='honorific',
            field=api.models.HonorificField(choices=[('MISTER', 'Mr'), ('MISS', 'Ms'), ('DOCTOR', 'Dr'), ('PROFESSOR', 'Prof')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='talk',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talk', to='api.TalkVideo'),
        ),
    ]
