# Generated by Django 2.1.5 on 2020-06-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200628_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='admin_comment',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
