# Generated by Django 2.1.5 on 2020-07-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_talk_admin_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='graduation_presentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='graduation_talk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='plenary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='poster',
            field=models.BooleanField(default=False),
        ),
    ]
