# Generated by Django 3.2.23 on 2024-01-14 03:28

import api.models
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200714_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='base_fee_affiliate',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('280'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='base_fee_full',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('280'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='base_fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('140'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='daily_fee_affiliate',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('60'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='daily_fee_full',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('60'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='daily_fee_student',
            field=api.models.MoneyField(decimal_places=2, default=Decimal('40'), max_digits=8),
        ),
    ]
