# Generated by Django 3.2.23 on 2024-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20240114_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='attending_italt',
            field=models.BooleanField(default=False),
        ),
    ]
