# Generated by Django 3.2.24 on 2024-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_registration_attending_italt'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='banquet_options',
            field=models.CharField(max_length=3, null=True, verbose_name='banquet options'),
        ),
    ]
