# Generated by Django 3.2.24 on 2024-02-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_registration_banquet_options'),
        ('api', '0052_alter_session_chair'),
    ]

    operations = [
    ]
