"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import logging.config
import os

from authorizenet.constants import constants as authorizenet_constants
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env(  # pylint: disable=invalid-name
    DJANGO_DEBUG=(bool, False), DJANGO_ALLOWED_HOSTS=(list, [])
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DJANGO_DEBUG")

ALLOWED_HOSTS = env("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Required for django-rest-auth registration
    "django.contrib.sites",
    # DRF
    "rest_framework",
    # filtering
    "django_filters",
    # allauth
    "allauth",
    "allauth.account",
    # django-rest-auth
    "rest_framework.authtoken",
    "rest_auth",
    "rest_auth.registration",
    "api",
    "corsheaders",
    "pandas",
    # For api documentation
    'drf_yasg',
]

# adapted from <https://lincolnloop.com/blog/django-logging-right-way/>
LOGGING_CONFIG = None
logging.config.dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "console": {
                "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
            }
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "console",
            },
            "file": {
                "class": "logging.FileHandler",
                "formatter": "console",
                "filename": "./logs/django.log",
            },
        },
        "loggers": {
            # root logger
            "": {"level": "DEBUG", "handlers": ["console", "file"]},
            # api module
            "api": {
                "level": "DEBUG",
                "handlers": ["console", "file"],
                "propagate": False,
            },
        },
    }
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",  # apply auth per view
    ),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "backend.wsgi.application"

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DEFAULT_DB = env.db()
DEFAULT_DB.update(
    {
        # needed for django-db-geventpool
        "ENGINE": "django_db_geventpool.backends.postgresql_psycopg2",
        "ATOMIC_REQUESTS": False,
        # needed for django-db-geventpool, or else conns never return to pool
        "CONN_MAX_AGE": 0,
        "OPTIONS": {"MAX_CONNS": 20},
    }
)
DATABASES = {"default": DEFAULT_DB}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"
    },
]

AUTH_USER_MODEL = "api.User"

# email as username, for django-allauth + django-rest-auth
# see <https://django-allauth.readthedocs.io/en/latest/advanced.html#custom-user-models>  # noqa 501
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_ADAPTER = "api.auth.CustomAccountAdapter"

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "static/"


# Required for django-rest-auth registration
SITE_DOMAIN_TO_ID_MAPPING = {"localhost:8080": 2, "itaws.ucsd.edu": 3}
SITE_DOMAIN = env("SITE_DOMAIN")
try:
    SITE_ID = SITE_DOMAIN_TO_ID_MAPPING[SITE_DOMAIN]
except KeyError:
    raise environ.compat.ImproperlyConfigured(
        "Invalid SITE_DOMAIN {}".format(SITE_DOMAIN)
    )

# Customizes django-rest-auth password reset behavior
REST_AUTH_SERIALIZERS = {
    "PASSWORD_RESET_SERIALIZER": "api.serializers.PasswordResetSerializer",
    "USER_DETAILS_SERIALIZER": "api.serializers.PrivateUserSerializer",
}

CORS_ORIGIN_ALLOW_ALL = True

# This is OK because Caddy sets the X-Forwarded-Proto correctly (i.e. according
# to actual scheme, not what a request header claims). If Caddy is no longer in
# use, you MUST verify that the security conditions in the Django documentation
# still applies:
# https://docs.djangoproject.com/en/2.1/ref/settings/#secure-proxy-ssl-header
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

DEFAULT_FROM_EMAIL = "ita@ucsd.edu"
DEFAULT_BCC_EMAIL = "ita.mail.backup@gmail.com"

# from <https://django-environ.readthedocs.io/en/latest/#tips>
# EMAIL_CONFIG = env.email_url("EMAIL_URL", default="consolemail://")
EMAIL_CONFIG = env.email_url(
    "EMAIL_URL", default="smtp+tls://smtp.ucsd.edu:587"
)

vars().update(EMAIL_CONFIG)

# Non-Django settings

FRONTEND_ROOT_DOMAIN = env("FRONTEND_ROOT_DOMAIN")

# Sandbox AuthorizeNet API credentials
AUTHORIZE_NET_API_CREDENTIALS_NAME = env("AUTHORIZE_NET_API_CREDENTIALS_NAME")
AUTHORIZE_NET_API_CREDENTIALS_TRANSACTION_KEY = env(
    "AUTHORIZE_NET_API_CREDENTIALS_TRANSACTION_KEY"
)
if DEBUG:
    AUTHORIZE_NET_ENVIRONMENT = authorizenet_constants.SANDBOX
    AUTHORIZE_NET_HOSTED_PAYMENT_PAGE_URL = (
        "https://test.authorize.net/payment/payment"
    )
    AUTHORIZE_NET_API_REDIRECT_DOMAIN = "https://127.0.0.1:3000"
else:
    AUTHORIZE_NET_ENVIRONMENT = authorizenet_constants.PRODUCTION
    AUTHORIZE_NET_HOSTED_PAYMENT_PAGE_URL = (
        "https://accept.authorize.net/payment/payment"
    )
    AUTHORIZE_NET_API_REDIRECT_DOMAIN = "https://ita.ucsd.edu"

# Storage for user-uploaded files, e.g. profile pictures, papers
SFTP_STORAGE_HOST = "3.128.57.152"
if DEBUG:
    ITAWEB_FILES_PATH = "workshop/ita_rebuild_files/local/"
else:
    ITAWEB_FILES_PATH = "workshop/ita_rebuild_files/prod/"
SFTP_STORAGE_ROOT = "/var/www/itaweb-react/" + ITAWEB_FILES_PATH
SFTP_STORAGE_PARAMS = {"username": "ubuntu", "key_filename": "./frontend.pem"}

DEFAULT_FILE_STORAGE = "storages.backends.sftpstorage.SFTPStorage"
MEDIA_URL = "https://ita.ucsd.edu/" + ITAWEB_FILES_PATH
